/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.openapitools.api

import org.openapitools.model.dto.CheckInRequest
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.responses.*
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.validation.annotation.Validated

import javax.validation.Valid

@RestController
@Validated
interface CheckinApi {

    @Operation(
        tags = ["default",],
        summary = "Online check-in",
        operationId = "checkinPost",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "Check-in successful"),
            ApiResponse(responseCode = "400", description = "Invalid parameters provided")
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/checkin"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun checkinPost(@Parameter(description = "", required = true) @Valid @RequestBody checkInRequest: CheckInRequest): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
