/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.12.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package org.openapitools.api

import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.validation.annotation.Validated
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired

import javax.validation.constraints.DecimalMax
import javax.validation.constraints.DecimalMin
import javax.validation.constraints.Email
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.NotNull
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size
import javax.validation.Valid

import kotlin.collections.List
import kotlin.collections.Map

@RestController
@Validated
interface RoutesApi {

    @Operation(
        tags = ["default",],
        summary = "List routes between two points",
        operationId = "routesGet",
        description = """""",
        responses = [
            ApiResponse(responseCode = "200", description = "A list of possible routes"),
            ApiResponse(responseCode = "400", description = "Invalid parameters provided")
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/routes"],
            produces = ["application/json"]
    )
    fun routesGet(@NotNull @Parameter(description = "", required = true) @Valid @RequestParam(value = "origin", required = true) origin: kotlin.String,@NotNull @Parameter(description = "", required = true) @Valid @RequestParam(value = "destination", required = true) destination: kotlin.String,@NotNull @Parameter(description = "", required = true) @Valid @RequestParam(value = "departure_date", required = true) @org.springframework.format.annotation.DateTimeFormat(iso = org.springframework.format.annotation.DateTimeFormat.ISO.DATE) departureDate: java.time.LocalDate,@Parameter(description = "Language code (e.g., en, ru)", required = true, schema = Schema(allowableValues = ["\"en\"", "\"ru\""])) @PathVariable("lang") lang: kotlin.String,@Parameter(description = "", schema = Schema(allowableValues = ["Economy", "Comfort", "Business"])) @Valid @RequestParam(value = "booking_class", required = false) bookingClass: kotlin.String?,@Min(0)@Parameter(description = "") @Valid @RequestParam(value = "max_connections", required = false) maxConnections: kotlin.Int?): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
